# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BADDialog
                                 A QGIS plugin
 BAD_Burned Area Detector
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-24
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Thomas Martinoli
        email                : th.martinoli96@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from .preview_window import PreviewWindow

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'BAD_dialog_base.ui'))


class BADDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(BADDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.Preview.clicked.connect(self.open_preview_window)

 #Interface dynamic elements
        self.cont_min = 0
        self.cont_max = 0
        
        self.doubleSpinBox_OWA_max12.setVisible(False)
        self.doubleSpinBox_OWA_max22.setVisible(False)
        self.doubleSpinBox_OWA_max13.setVisible(False)
        self.doubleSpinBox_OWA_max23.setVisible(False)
        self.doubleSpinBox_OWA_min12.setVisible(False)
        self.doubleSpinBox_OWA_min22.setVisible(False)
        self.doubleSpinBox_OWA_min13.setVisible(False)
        self.doubleSpinBox_OWA_min23.setVisible(False)

        self.pushButton_OWA_max1.clicked.connect(lambda: self.add_spinbox("max1"))
        self.pushButton_OWA_max2.clicked.connect(lambda: self.add_spinbox("max2"))
        self.pushButton_OWA_min1.clicked.connect(lambda: self.add_spinbox("min1"))
        self.pushButton_OWA_min2.clicked.connect(lambda: self.add_spinbox("min2"))
        

    def open_preview_window(self):
        self.preview_dialog = PreviewWindow(self)
        self.preview_dialog.show()

                    
    #############

    def add_spinbox(self, key):
        mapping = {
            "max1": [self.doubleSpinBox_OWA_max12, self.doubleSpinBox_OWA_max13],
            "max2": [self.doubleSpinBox_OWA_max22, self.doubleSpinBox_OWA_max23],
            "min1": [self.doubleSpinBox_OWA_min12, self.doubleSpinBox_OWA_min13],
            "min2": [self.doubleSpinBox_OWA_min22, self.doubleSpinBox_OWA_min23],
        }

        counter_attr = f"cont_{key}"
        if not hasattr(self, counter_attr):
            setattr(self, counter_attr, 0)

        count = getattr(self, counter_attr)
        spinboxes = mapping[key]

        if count < len(spinboxes):
            spinboxes[count].setVisible(True)
            setattr(self, counter_attr, count + 1)
        if count + 1 >= len(spinboxes):
            getattr(self, f"pushButton_OWA_{key}").setEnabled(False)
 
